#!/bin/bash
# postinstall of tech.blackdeep.knaif.model — "download the AI model now" (D13).
#
# build-pkg.sh installs this as `postinstall` beside a generated model.env naming MODEL, read from
# the model manifest the payload ships (never typed by hand). Runs `knaif models pull` as the
# console user so the model lands in their ~/.knaif/models — which `models pull` also keeps out of
# Time Machine (D18). Setup waits for it; a failure is reported, never fatal. Installer shows only
# "Running package scripts…" meanwhile, so notifications say when the download starts and ends.

here="$(dirname "$0")"
# shellcheck source=common.sh
. "$here/common.sh"
# shellcheck disable=SC1091  # generated by build-pkg.sh
. "$here/model.env"

knaif="$KNAIF_ROOT/bin/knaif"
retry="knaif models pull $MODEL"

user="$(console_user)"
if [ -z "$user" ]; then
  log "skipping the model download: nobody is logged in to download it for. Later: $retry"
  exit 0
fi
if as_user "$user" "$knaif" models list 2>/dev/null |
  awk -v m="$MODEL" '$1 == m && $2 == "installed" { found = 1 } END { exit !found }'; then
  log "$MODEL is already installed for $user"
  exit 0
fi

log "downloading $MODEL for $user"
notify_user "$user" "Downloading the AI model (about 2.5 GB). Setup finishes when it is done, usually in 5 to 15 minutes."
if as_user "$user" "$knaif" models pull "$MODEL"; then
  log "$MODEL is installed"
  notify_user "$user" "The AI model is downloaded. Setup is finishing."
else
  log "could not download $MODEL; knaif is installed anyway. Retry: $retry"
  notify_user "$user" "The AI model did not download, but knaif is installed. Run \"$retry\" later; it continues where it stopped."
fi
exit 0
